name: Build and Deploy React App

on:
  push:
    branches:
      - main  # your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Apply npm resolutions fix
        run: npx npm-force-resolutions

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy build files to server /var/www/html/banking-app
        uses: appleboy/scp-action@v0.1.8
        with:
          host: 3.7.43.81
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "/var/www/html/banking-app"
